
version: '3.4'
services:
  reservations-database9:
    # build: ./database
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-database9:1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  reservations-backend9:
    # build: ./backend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-backend9:1.0
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - "reservations-database9"
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"
  reservations-frontend9:
    # build: ./frontend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-frontend9:1.0
    ports:
      # - 3000:3000
      - 80:80
      # - 443:443
    depends_on:
      - "reservations-backend9"
volumes:
  db-data:
  