
version: '3.4'
services:
  reservations-database13:
    # build: ./database
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-database13:1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  reservations-backend13:
    # build: ./backend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-backend13:1.0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "reservations-database13"
    command: >
      sh -c "flask db upgrade && gunicorn -w 4 -b 0.0.0.0 app:app"
  reservations-frontend13:
    # build: ./frontend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: blasemoylan/reservations-frontend13:1.0
    ports:
      # - 3000:3000
      - 80:80
      # - 443:443
    depends_on:
      - "reservations-backend13"
volumes:
  db-data:
  