"""empty message

Revision ID: 314787cbc0dc
Revises: e7ac500a22ee
Create Date: 2023-05-07 14:39:35.965019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314787cbc0dc'
down_revision = 'e7ac500a22ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
