"""empty message

Revision ID: 35caf84437de
Revises: f389388de06c
Create Date: 2023-05-06 10:20:10.023337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35caf84437de'
down_revision = 'f389388de06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('table_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unavailable')
    # ### end Alembic commands ###
