"""empty message

Revision ID: 38026b862286
Revises: b64c61bf2459
Create Date: 2023-05-04 08:07:07.561041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38026b862286'
down_revision = 'b64c61bf2459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wait__list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('costumer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('wait__list_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['costumer_id'], ['id'])
        batch_op.drop_column('reservation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wait__list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wait__list_ibfk_1', 'reservations', ['reservation_id'], ['id'])
        batch_op.drop_column('costumer_id')
        batch_op.drop_column('table_id')
        batch_op.drop_column('date')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
