"""empty message

Revision ID: 85d33273c2ca
Revises: 9cae36282122
Create Date: 2023-05-02 09:53:02.226569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d33273c2ca'
down_revision = '9cae36282122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_set_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_size', sa.Integer(), nullable=False),
    sa.Column('num_of_tables', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('num_of_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('num_of_tables')
    op.drop_table('table_set_up')
    # ### end Alembic commands ###
