"""empty message

Revision ID: 91a3f6a6402d
Revises: 85d33273c2ca
Create Date: 2023-05-02 10:00:33.020066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91a3f6a6402d'
down_revision = '85d33273c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('num_of_tables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('num_of_tables',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.DATE(), nullable=False),
    sa.Column('hour', mysql.TIME(), nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name='num_of_tables_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('used_tables')
    # ### end Alembic commands ###
