"""empty message

Revision ID: 9cae36282122
Revises: 099c69e47995
Create Date: 2023-05-01 11:20:00.718810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cae36282122'
down_revision = '099c69e47995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costumer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('reservations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['costumer_id'], ['id'])
        batch_op.drop_column('custumer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custumer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservations_ibfk_1', 'user', ['custumer_id'], ['id'])
        batch_op.drop_column('costumer_id')

    # ### end Alembic commands ###
