"""empty message

Revision ID: e7ac500a22ee
Revises: 35caf84437de
Create Date: 2023-05-06 10:49:41.679171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7ac500a22ee'
down_revision = '35caf84437de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wait__list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_size', sa.Integer(), nullable=False))
        batch_op.drop_constraint('wait__list_ibfk_1', type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wait__list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('wait__list_ibfk_1', 'table', ['table_id'], ['id'])
        batch_op.drop_column('table_size')

    # ### end Alembic commands ###
