"""empty message

Revision ID: f389388de06c
Revises: 5889f8adc50a
Create Date: 2023-05-04 09:31:03.269978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f389388de06c'
down_revision = '5889f8adc50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.drop_column('hour')
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('hour', mysql.TIME(), nullable=False))
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
